version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: chatapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=chatapp
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=test-secret-key-for-local-development
    command: sh -c "sleep 10 && ./migrate -migrate -seed && ./main"

volumes:
  postgres_data: